### ISSUE TITLE
Add WeekendJam archive playlist to repertoire

### ISSUE THREAD

**Issue by cleary** [tmhglnd/collaborative-coding-practices#1]
Hi!

The Estuary WeekendJams have been a weekly collaborative, improvised livecoding institution since late 2020 - we started recording them early 2021 and archiving on my personal yt channel before moving to the eulerroom channel just over a year ago. 

The eulerroom playlist will be the final home for this archive, I'm in the process of transferring 2.5 years of videos across from my personal channel.

I think this would be good to link in "Repertoire" in the README.md:
https://www.youtube.com/playlist?list=PLMBIpibV-wQLvP7jitjnV9E61DfV11235

I compiled some youtube stats in [this spreadsheet](https://docs.google.com/spreadsheets/d/1NIsV2rK5k9Ni8TFQkLYRfWEjbSB9nvbaWEmWR5VRyME/edit?usp=sharing)
We have run over 160 jams, with participation from over 60 unique livecoders in the 3+ years it's been running

**Comment by tmhglnd** [comment]
Thanks for the suggestion to include this, I will!
